services:
  anomaly-detection:
    build:
      context: ../anomaly-detection
      dockerfile: Dockerfile
    container_name: anomaly-api
    volumes:
      - ../anomaly-detection:/app
    working_dir: /app
    environment:
      - MQTT_HOST=hivemq
      - MQTT_PORT=1883
    ports:
      - "8002:8002"
    command: >
      uvicorn main:app --host 0.0.0.0 --port 8002 --reload
#     networks:
#       - scada-net

# networks:
#   scada-net:
#     external: true
