version: "3.8"

services:
  ad-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ad-fastapi-service
    ports:
      - "8001:8001"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./app:/app/app
      - ./core:/app/core
      - ./outputs:/app/outputs
      - ./train_data:/app/train_data                    # If you load device CSVs/models from here
      - ./storage:/app/storage            # For saved LSTM models
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
